### ISSUE TITLE
Scratch Sound API

### ISSUE THREAD

**Issue by wgyt** [wgytwebsites/api.wgyt.tk#1]
An API for Scratch Sound.
The endpoint is /scratchsound
RE @ScratchSound and @Namirah-Rahman

**Comment by wgyt** [comment]
We would need a page on ScratchSound's website listing all of the songs. @ScratchSound is working on getting this done.

**Comment by wgyt** [comment]
Closing because scratchsound is shut down.

**Comment by Namirah-Rahman** [comment]
☹️
